---
title: Steph Explores
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
description: Exploring trails and waterways in Manitoba and northwestern Ontario
first_published: 2016
email: stephanie.paige@hotmail.com
baseurl: 
url: http://stephexplores.ca
social:
  instagram: https://www.instagram.com/steph.explores/
  youtube: https://www.youtube.com/channel/UCcrrpGUoDCTznp0YKyo3O3Q
  pinterest: https://www.pinterest.com/stephexplores/
markdown: kramdown
